site_name: anymap-ts
site_description: A Python package for creating interactive maps with anywidget and TypeScript
site_author: giswqs
site_url: https://ts.anymap.dev
repo_url: https://github.com/opengeos/anymap-ts

copyright: "Copyright &copy; 2025 Qiusheng Wu"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    # logo: assets/logo.png
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: false
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb"]

markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

extra_css:
    - stylesheets/extra.css

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - Changelog: https://github.com/opengeos/anymap-ts/releases
    - Report Issues: https://github.com/opengeos/anymap-ts/issues
    - Live Examples: examples/index.html
    - TypeScript:
          - Overview: typescript/index.md
          - Examples:
                - MapLibre: typescript/examples/maplibre.md
                - Leaflet: typescript/examples/leaflet.md
                - Mapbox: typescript/examples/mapbox.md
                - Cesium: typescript/examples/cesium.md
                - DeckGL: typescript/examples/deckgl.md
                - OpenLayers: typescript/examples/openlayers.md
                - Potree: typescript/examples/potree.md
                - KeplerGL: typescript/examples/keplergl.md
                - COG Layer: typescript/examples/cog_layer.md
                - Zarr Layer: typescript/examples/zarr_layer.md
    - Cesium:
          - cesium/cesium.ipynb
    - DeckGL:
          - deckgl/deckgl.ipynb
          - deckgl/bitmap_layer.ipynb
          - deckgl/column_layer.ipynb
          - deckgl/contour_layer.ipynb
          - deckgl/geojson_layer.ipynb
          - deckgl/geohash_layer.ipynb
          - deckgl/great_circle_layer.ipynb
          - deckgl/gridcell_layer.ipynb
          - deckgl/h3_cluster_layer.ipynb
          - deckgl/h3_hexagon_layer.ipynb
          - deckgl/heatmap_layer.ipynb
          - deckgl/hexagon_layer.ipynb
          - deckgl/icon_layer.ipynb
          - deckgl/mvt_layer.ipynb
          - deckgl/polygon_layer.ipynb
          - deckgl/quadkey_layer.ipynb
          - deckgl/s2_layer.ipynb
          - deckgl/scatterplot_layer.ipynb
          - deckgl/scenegraph_layer.ipynb
          - deckgl/simplemesh_layer.ipynb
          - deckgl/solidpolygon_layer.ipynb
          - deckgl/terrain_layer.ipynb
          - deckgl/text_layer.ipynb
          - deckgl/tile3d_layer.ipynb
          - deckgl/tile_layer.ipynb
          - deckgl/trips_layer.ipynb
          - deckgl/wms_layer.ipynb
    - KeplerGL:
          - keplergl/keplergl.ipynb
    - Leaflet:
          - leaflet/leaflet.ipynb
    - MapLibre:
          - maplibre/maplibre.ipynb
          - maplibre/arc_layer.ipynb
          - maplibre/buildings_3d.ipynb
          - maplibre/choropleth.ipynb
          - maplibre/clustering.ipynb
          - maplibre/cog_layer.ipynb
          - maplibre/colorbar.ipynb
          - maplibre/control_grid.ipynb
          - maplibre/data_export.ipynb
          - maplibre/deck_advanced_layers.ipynb
          - maplibre/deck_layers.ipynb
          - maplibre/feature_query_filter.ipynb
          - maplibre/flatgeobuf.ipynb
          - maplibre/globe_projection.ipynb
          - maplibre/image_overlay.ipynb
          - maplibre/layer_management.ipynb
          - maplibre/lidar_layer.ipynb
          - maplibre/maplibre_heatmap.ipynb
          - maplibre/markers.ipynb
          - maplibre/measure.ipynb
          - maplibre/pmtiles_layer.ipynb
          - maplibre/pointcloud_layer.ipynb
          - maplibre/popups.ipynb
          - maplibre/print_control.ipynb
          - maplibre/route_animation.ipynb
          - maplibre/search_control.ipynb
          - maplibre/sky_fog.ipynb
          - maplibre/solara.ipynb
          - maplibre/split_map.ipynb
          - maplibre/style_switcher.ipynb
          - maplibre/terrain_3d.ipynb
          - maplibre/time_slider.ipynb
          - maplibre/to_html.ipynb
          - maplibre/tooltip.ipynb
          - maplibre/ui_controls.ipynb
          - maplibre/video_layer.ipynb
          - maplibre/zarr_layer.ipynb
    - Mapbox:
          - mapbox/mapbox.ipynb
          - mapbox/choropleth.ipynb
          - mapbox/cog_layer.ipynb
          - mapbox/deck_layers.ipynb
          - mapbox/layer_management.ipynb
          - mapbox/markers.ipynb
          - mapbox/popups_tooltips.ipynb
          - mapbox/terrain_3d.ipynb
          - mapbox/ui_controls.ipynb
          - mapbox/vector_data.ipynb
    - OpenLayers:
          - openlayers/openlayers.ipynb
    - Potree:
          - potree/potree.ipynb
    - API Reference:
          - anymap_ts module: anymap_ts.md
          - base module: base.md
          - basemaps module: basemaps.md
          - maplibre module: maplibre.md
          - mapbox module: mapbox.md
          - leaflet module: leaflet.md
          - openlayers module: openlayers.md
          - deckgl module: deckgl.md
          - cesium module: cesium.md
          - keplergl module: keplergl.md
          - potree module: potree.md
          - utils module: utils.md